
[build]

publish = "dist"
command = "yarn generate"

[functions]
  directory = "netlify/functions"

[[redirects]]
from = "/subscribe"
to = "/.netlify/functions/subscribe"
status = 200

[[redirects]]
from = "/api/get-joke"
to = "/.netlify/functions/get-todays-joke"
status = 200
